# Generated by Django 5.2.14 on 2026-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tagger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageoutput",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("loaded", "Loaded"),
                    ("checking", "Checking"),
                    ("accepted", "Accepted"),
                    ("needs_rerun", "Needs rerun"),
                    ("blocked", "Blocked"),
                ],
                default="not_started",
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="stageoutput",
            constraint=models.UniqueConstraint(
                fields=("document", "stage"), name="unique_stage_output_per_document"
            ),
        ),
    ]
